### ISSUE TITLE
Vulnerability

### ISSUE THREAD

**Issue by angeloocana** [DercilioFontes/city-qo-l#1]
Hi Dercilio!

Great project!

I was reviewing your code and I just found a vulnerability,
Do you know where it is and how to fix it?

Good luck with your interview process at Kinaxis!

**Comment by DercilioFontes** [comment]
Hi Angelo,

I think you are talking about the Mapbox API key in the commit history. I will remove it.

Thank you.

**Comment by angeloocana** [comment]
It is not that,
it is a place where a hacker could inject scripts.

**Comment by DercilioFontes** [comment]
Humm. Ok. 

You are talking about the use of `dangerouslySetInnerHTML`? I'll remove it and do it in another way. 

But you said inject. So, it should be in the request query with input from the user. I'll check that also

I removed that commit with the Mapbox API key.

**Comment by angeloocana** [comment]
yes!

but you don't need to remove it, you just need to sanitize the content,
you can use a library like https://github.com/cure53/DOMPurify

**Comment by DercilioFontes** [comment]
Implemented. Thank you.
